language: python
sudo: enabled
addons:
  chrome: stable
before_install:
  - sudo apt-get install wget unzip
  - pip install -r requirements.txt
install:
  - sh download_drivers.sh
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  #- python test.py
